name: settimana_santa
description: Settimana santa in penisola sorrentina

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  assets_audio_player: ^3.0.4+1
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  intl: ^0.17.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon.png
    - assets/images/weather/
    - assets/images/miserere.png
    - assets/audios/

  fonts:
    - family: Morris
      fonts:
        - asset: assets/fonts/morris_roman/MorrisRomanBlack.ttf
    - family: AssetAudioPlayer
      fonts:
        - asset: assets/fonts/AssetAudioPlayer.ttf
